name: CCC

on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          cache: 'go'
          path: /home/runner/go
          key: ${{ runner.os }}-go

      - name: Setup Dependencies
        run: |
          nohup --version
          sudo apt-get update
          sudo apt-get install libpcap-dev
          rm -rf test.html
          cat urls.txt |sort|uniq|tee urls.txt

      - name: Setting up ProjectDiscovery tools
        env:
          GO111MODULE: on
        run: |
          go install -v github.com/projectdiscovery/katana/cmd/katana@latest


      - name: KAK listen
        run: |
          wget https://github.com/chaitin/xray/releases/download/1.9.3/xray_linux_amd64.zip
          unzip xray_linux_amd64.zip
          mv xray_linux_amd64 xray

          ./xray
          /usr/bin/nohup ./xray webscan --plugins xss,sqldet,xxe,cmd-injection,upload,path-traversal,dirscan,redirect,jsonp --listen 127.0.0.1:7777  --html-output test.html &
        shell: bash
        
      - name: Running Scanner
        timeout-minutes: 340
        continue-on-error: true
        run: |
          for i in $(cat urls.txt); do katana -u $i -cs ${i#*//} -aff -H -jc -d 7 -proxy http://127.0.0.1:7777; done
          #katana -u "http://testasp.vulnweb.com" -aff -H -jc -d 7 
          cat test.html
        shell: bash

      - name: Sorting the output results
        run: |
          find test.json -type f -exec sort {} -o {} \;
        shell: bash

      - name: Create local changes
        run: |
          git add test.html
      - name: Commit results to Github
        run: |
          git config --local user.email "jinbao1986@qq.com"
          git config --global user.name "TNT"
          git commit -m "InCloud Report" -a --allow-empty
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
